### ISSUE TITLE
PQ doesn't work properly if you send no (scalar?) parameters

### ISSUE THREAD

**Issue by delgermurun** [graphcool/api-bugs#118]
```
query ($user_id: ID!) {
  SomeUserExists(
    filter: {
      id: $user_id
    }
  )
}
```

I've above simple PQ on POST Create action. Post type has optional `description` field.

If you don't send any parameter, mutation throws `Insufficient permission` even though there is an authenticated user. The bug occurs even when I send relation params (like userId), but no scalar(?) params.

```
mutation {
  createPost {
    id
  }
}
```

But works fine, if you send `description` parameter. Like this

```


mutation {
  createPost (description: "ddd") {
    id
  }
}
```

**Comment by marktani** [comment]
Because permissions work on a field-level, this is the current intended behaviour: when no scalar fields are part of the mutation, the permission will find no field that it's applicable for, so it does not match that mutation, therefore permission is not granted.

We should think about allowing a finer-grained control of permissions that make the creation without any scalar field possible. Feel free to create [a feature request](https://github.com/graphcool/feature-requests) about this 🙂

**Comment by delgermurun** [comment]
We struggled on this issue for many hours. You guys should've told this earlier :(

Created FR issue https://github.com/graphcool/feature-requests/issues/245

**Comment by marktani** [comment]
> You guys should've told this earlier :(

I  absolutely agree, sorry for the inconvenience. Thanks for the feature request, we will think of the best way to approach this issue!
