### ISSUE TITLE
Strange behavior from the image cropping api

### ISSUE THREAD

**Issue by Aetherall** [graphcool/api-bugs#158]
Hi!
I uploaded a 3840x1080 pic on the server, and I'm expecting this link :
https://images.graph.cool/v1/cj3n0fa4147rf0173ledl3s1i/cj4l1otvm00pp0187lbqjsb9r/1380x0:2460x1080
to give me a square of 1080x1080 ...
Is this an expected behavior ?

**Comment by marktani** [comment]
Thanks for the question! This is indeed expected behaviour.

`1380x0:2460x1080` means "start from 1380 and take the next 2460 pixels". If you want 1080 instead, you need to say `1380x0:1080x1080`. If you have further questions about the Image API, please open a new in [this repo](https://github.com/graphcool/serverless-image-proxy).

**Comment by Aetherall** [comment]
My bad! Thanks!

**Comment by marktani** [comment]
Absolutely! 👍
