### ISSUE TITLE
Handle missing data property in returned object in SE functions gracefully

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#195]
**What is the current behavior?**

Returning an unexpected shape in a schema extension results in an internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Setup a new schema extension function like this:

```graphql
type MyPayload {
 success: Boolean!
}

extend type Mutation {
 myMutation(
   argument: String!
 ): MyPayload
}
```

and implement the function:

```js
 return { data: { success: true } }
```

all is well! However, if you use this instead:

```js
 return { data: { badField: true } }
```

you'll receive an internal server error.

**What is the expected behavior?**

Introduce a new error code + message that helps to understand the problem.

**Comment by marktani** [comment]
In case of a required field, the typical "null bubbling" behaviour is expected as well.

**Comment by marktani** [comment]
This is now fixed 💚

**Comment by marktani** [comment]
This still happens when `data` is not part of the returned object:

```
return { success: true }
```

results in an internal server error.

**Comment by kbrandwijk** [comment]
@marktani Your last comment triggered something with me. Wouldn't it make more sense if you could return your object from a function, and the system would wrap the return value automatically, or put any thrown errors in the error object?

To prevent breaking changes :wink: you might implement it like this: if top-level return value is `data` then return as is, otherwise wrap in `data { ... }`. That would keep all existing functions working as-is.

**Comment by marktani** [comment]
I actually think the current API is better, as it allows for a unified experience for inline functions and webhooks. In webhooks, there's no way to control how catching errors should be handled.

**Comment by mattfysh** [comment]
Agreed - event in, event out - allows you to compose, which is probably only important for request pipeline functions, but then it makes sense to make input/output consistent across all function types

**Comment by mattfysh** [comment]
@kbrandwijk I could be wrong, but I think you may be conflating events and queries

**Comment by kbrandwijk** [comment]
@mattfysh What I described was the way you return a value from a SE, and how that translates into the query result. To me, that feels inconsistent. SE's follow the same format as SSS and RP for return values, but for SSS and RP that's not a problem, because those return values are not translated directly into query results, so the issue I mentioned only surfaced since the introduction of SE's.

**Comment by mattfysh** [comment]
If you use the `TRANSFORM_PAYLOAD` hook point of an RP function, that should translate directly into a query response. I think there may be some confusion still around what is a query and what is an event... perhaps it helps to express it as:

`response.data[operationName] = fn(event).data`

Where:

* `response` is your JSON HTTP response
* `event` is the type of object that is both an input and an output of a Graphcool Function (`fn`)
* `operationName` is defined alongside your function name in the GraphQL function editor - it's defined either in your `extend Query/Mutation` code, or when you selected the event trigger e.g. User is Created / `createUser`

**Comment by kbrandwijk** [comment]
I meant that the query response inserts the operation name between the `data` node and the result object.

**Comment by mattfysh** [comment]
@kbrandwijk sure, I assume that's because the operation name is opaque to the Graphcool Function, it does not deal in operation names, or requests/responses - only events :)

**Comment by kbrandwijk** [comment]
@nilan What's your take on https://github.com/graphcool/api-bugs/issues/195#issuecomment-323304380?
