### ISSUE TITLE
Invalid project name error message is inaccurrate

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#211]
![image](https://user-images.githubusercontent.com/1780597/28747871-6eca17b2-74a9-11e7-9199-36da6eb4b65f.png)

should mention alphanumeric, starting with an uppercase letter.

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/console/issues/805

**Comment by DevanB** [comment]
I noticed this issue today:

```bash
10:57 $ graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews-test
✖  Error: 'Hackernews-test' is not a valid project name. It must begin with an uppercase letter.

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

Technically, the project name does start with an uppercase letter, but the issue is the hyphen. Specifying in the error message something like "It must begin with an uppercase letter, and must only contain alphanumeric characters" would cover this instance of the error.
