### ISSUE TITLE
Mutation method signatures with enum properties changed causing breaking change

### ISSUE THREAD

**Issue by wallslide** [graphcool/api-bugs#228]
**What is the current behavior?**

Mutations that reference enum properties now use the enum's name directly as the type's name, instead of a graphcool-generated type name.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

I'm getting error messages such as:
```
GraphQL error: Variable '$eventStyle' cannot be non input type 'EVENT_EVENT_STYLE!'
```
Where the type for variable $eventStyle used to be the graphcool-generated typename `EVENT_EVENT_STYLE`, but has now been changed to `EVENT_STYLE`, which is the name of the enum being referenced.

This change causes any mutations referencing enums to break.

**Comment by marktani** [comment]
I'm sharing my reply here with everyone for better visibility:

> We won't revert this, as the current behaviour is actually intended. In fact, we were not aware of this breaking change, so I'm super sorry about how this went down. Normally we would have announced this in advance to give a heads up.

If you need help with adjusting your code to this change or have any other questions, please reach out to support@graph.cool :pray:

**Comment by marktani** [comment]
I'll leave this issue open for some time so anyone running into the same issue can find it easier.

**Comment by marktani** [comment]
More information: Indeed, this is also breaking queries that use an input variable for enum fields on a filter object.

**Comment by marktani** [comment]
More information:

> The name used is taken directly from the enum name in your project setup, so in some cases it might be possible to fix the issue by changing the enum name on the server.

**Comment by mattfysh** [comment]
Bugs happen and breaking changes are mismanaged and pushed out with no heads up -- we get that, and we've all been there.

However, a couple of things that are super concerning...

1. When the breaking change was discovered to have been pushed out and affecting real & live production applications, there was no alert system in place to inform the user base. Had I been given a heads up, I could have had a fix up and running in our environments within 5 minutes of the alert. Unfortunately, the problem was discovered 3 hours later during a demo of our product with a potential client. I'm sure you will agree - this is the least ideal scenario

2. "We won't revert this" is an unreasonable response, and lacks a display of ownership on behalf of Graphcool. The change should have been _immediately_ reverted to restore service to production applications, and managed correctly before being re-deployed.

**Comment by marktani** [comment]
Hey Matt,

thanks so much for your feedback regarding this matter, we clearly did not handle this correctly. I now reached out to everyone who is potentially affected by this change to help them adjusting to the new behaviour.

Usually, we announce breaking changes months in advance and send periodic reminders, so developers can smoothly transition their apps. Unfortunately, we weren't able to implement this policy in this case, and I am terribly sorry about this.

It was a tough decision, but we still decided to not roll back this change after thorough consideration, as the current behaviour is intended and should have been put in place already two months ago.

I want apologize again for the troubles. As I reached out to developers individually, I am now closing this issue. Thanks for all your help! 🙏
