### ISSUE TITLE
Also include DateTime in schema export 

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#42]

**Comment by tafelito** [comment]
I'm using the extension https://github.com/kumarharsh/graphql-for-vscodeallows, which allows you to do such things like auto-complete or schema validation, and more. I exported the schema from the console to my project. The schema has some DateTime fields,  and because it's not a a native date type, I'm getting the error `Type "DateTime not found`

**Comment by marktani** [comment]
This can now be done with https://github.com/graphcool/get-graphql-schema:

```sh
npm install -g get-graphql-schema
get-graphql-schema ENDPOINT_URL > schema.graphql
```

@tafelito can you confirm that this works for you?

**Comment by marktani** [comment]
Closing this. Feel free to comment here if you have questions.
