### ISSUE TITLE
Function does not affect payload response for fields with a defaultValue

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#68]
This function should flip the `isPaid` boolean - it works in test run, but not with an actual mutation

```js
module.exports = function (event, cb) {
  event.data.isPaid = !event.data.isPaid
  return {event}
}
```

This is the mutation:

```
 mutation ($id: ID!, $description: String!, $amount: Float!, $plan: PURCHASE_PLAN!, $stripeId: String!, $stripeToken: String!) {
    createPurchase(
      description: $description
      userId: $id
      amount: $amount
      plan: $plan
      stripeToken: $stripeToken
      stripeId: $stripeId
      ) 
      {
        id
        description
        amount
        plan
        isPaid
      }
  }
```

Note that `isPaid` is not part of the actual mutation in put, but the field has a default value of `false` - that's not correctly handled for the different function inputs.

**Comment by kbrandwijk** [comment]
This basically comes down to **'defaultValue for fields set _after_ RP'**. This is because there are two symptoms:
1. fields with a defaultValue that are not part of the mutation don't have that defaultValue set in RP
2. setting the value of a field with a defaultValue in an RP will not be persisted (because overwritten after the RP by the defaultValue)
